### ISSUE TITLE
Game: checkWallPosition

### ISSUE THREAD

**Issue by CeciliaComar** [AM311/Quoridor#6]
Verifica che la posizione in cui si è intenzionati a mettere il muro sia possibile (non comporti quindi la sovrapposizione con altri muri/non sia per metà o interamente fuori dalla scacchiera)

**Comment by AM311** [comment]
@matfumis alcuni refactors per migliorare il codice:
- cambiare il nome del parametro "orientation" in "horizontal"/"vertical" o qualcosa di simile, affinché sia chiaro come è posizionato il muro (è orizzontale? SI/NO). Allo stato attuale non è chiaro quale sia la convenzione.
- Sostituire l'8 con la costante in GameBoard.

In fase successiva, valuterei di rendere più modulare il metodo estraendo dei sotto-metodi per rendere più snello e comprensibile il codice.
